export const ADD_SITE = "ADD_SITE";
export const TOGGLE_SITE_MAP_OPEN = "TOGGLE_SITE_MAP_OPEN";
export const SET_MASTER_API_KEY = "SET_MASTER_API_KEY";
export const ADD_API_KEY = "ADD_API_KEY";
export const UPDATE_API_KEY = "UPDATE_API_KEY";
export const SET_EMAIL = "SET_EMAIL";
export const ADD_TEAM_MEMBER = "ADD_TEAM_MEMBER";
export const UPDATE_TEAM_MEMBER = "UPDATE_TEAM_MEMBER";
export const RESET_STORE = "RESET_STORE";

export const LOGIN_FETCH = "LOGIN_FETCH";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const REGISTER_RESET = "REGISTER_RESET";
export const REGISTER_FETCH = "REGISTER_FETCH";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const ORG_FETCHING = "ORG_FETCHING";
export const ORG_SET = "ORG_SET";
export const ORG_ERROR = "ORG_ERROR";

export const TEAM_FETCHING = "TEAM_FETCHING";
export const TEAM_ERROR = "TEAM_ERROR";
